# Generated by Django 5.0.6 on 2025-02-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('tel', models.DecimalField(decimal_places=0, max_digits=4)),
                ('registro', models.DateField()),
                ('acceso', models.DateField()),
            ],
        ),
    ]
